---
- name: Install Apache.
  hosts: all
  become: true
  gather_facts: true

  vars:
    apache_package: apache2
    apache_service: apache2

  handlers:
    - name: restart apache
      ansible.builtin.service: 
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - name: Override Apache vars for RedHat.
      ansible.builtin.set_fact:
        apache_package: httpd
        apache_service: httpd
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: Ensure Apache is installed.
      ansible.builtin.package:
        name: "{{ apache_package }}"
        state: present
    
    - name: Copy a WebPage
      ansible.builtin.copy:
        content: |
          <html>
          <head><title>Hello World</title></head>
          <body>HELLO WORLD!!!</body>
          </html>
        dest: "/var/www/html/index.html"
        mode: 0644
      notify: restart apache

    - name: Ensure Apache is running on boot.
      ansible.builtin.service:
        name: "{{ apache_service }}"
        state: started
        enabled: true