---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  
  tasks:
  - name: Verify if we can reach GOOGLE!
    ansible.builtin.uri:
      url: https://google.com
      status_code:
        - 200
      return_content: true